spring:
  application:
    name: implementoMS
  datasource:
    url: jdbc:mysql://localhost:3306/implemento_db
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8087

springdoc:
  api-docs:
    enabled: true
    version: openapi-3-0
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/