spring.application.name=canchaMS

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3307/cancha_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true