spring:
  application:
    name: sedeMS
  datasource:
    url: jdbc:mysql://localhost:3307/sede_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

springdoc:
  api-docs:
    enabled: true
    version: openapi-3-0
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

