spring:
  application:
    name: arriendoImplementoMS
  datasource:
    url: jdbc:mysql://localhost:3307/arriendo_implemento_db
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/